version: '3.8'

services:
  ielts-course-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ielts-course-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    stdin_open: true
    tty: true
